# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, unique=True)),
                ('counter', models.IntegerField(default=0)),
                ('type', models.CharField(default='DEFAULT', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Click Counters',
                'verbose_name': 'Click Counter',
            },
        ),
    ]
